### ISSUE TITLE
Using eudgc with react native (BigInt problem)?

### ISSUE THREAD

**Issue by bluepuma77** [Scopevisio/eudgc#1]
I would like to use the [eudgc library](https://github.com/Scopevisio/eudgc) on mobile with [React Native](https://github.com/facebook/react-native). 

When I create a React Native app with eudgc integrated (example code: [snack.expo.dev](https://snack.expo.dev/PQ0n6arKN)), I receive the error `Can’t find variable: BigInt` when the app is compiled. 

How to reproduce: I usually just scan the "Run on your device" QR code on the Expo website from within the Android Expo app, then the compilation process is started.

During problem research I found a [comment on react-native GitHub](https://github.com/facebook/react-native/issues/28492#issuecomment-824698934):
> You are importing a package somewhere that requires BigInt as a dependency. For the most part ReactNative uses JavaScriptCore which may not have the support of BigInt.

And [core-js](https://github.com/zloirock/core-js) states (all the way at the bottom): 
> ES BigInt can't be polyfilled since it requires changes in the behavior of operators, you could find more info here. You could try to use JSBI.

Is there a way to get eudgc to run with React Native?

**Comment by srutz** [comment]
Hi Bluepuma, this question has been asked before and I received feedback from Pietro from Italy that he solved that issue. 

Maybe this was helpful

https://github.com/facebook/react-native/issues/28492#issuecomment-824698934 

It seems like react-native doesn't support the newer ECMA features and BigInt happens to be one of them. 
I haven't tried to use the lib with react-native but I will try and add some recipes/solutions in the README if I find any.

If you could share your findings, that would also be greatly welcomed. Thanks.

**Comment by alexduca** [comment]
Someone find a solution for implementing with react-native??

**Comment by srutz** [comment]
Hi Alexduca, see above. The workaround here https://github.com/facebook/react-native/issues/28492#issuecomment-824698934  seemed to fix the issue.
Maybe newer versions of React-Native have more recent ECMA-Script support. Eventually this would also fix the issue.

**Comment by alexduca** [comment]
Hello @srutz !
I read all the topic but i didn't understand where i have to change because i didn't have a `shim.js` file in my project.

**Comment by alexduca** [comment]
Someone can help me please
